annotations:
  screwdriver.cd/chainPR: true

shared:
  image: node:12
  steps:
    - echo: echo hi
    
jobs:
  main:
    requires: [~commit, ~pr]
  internal_fork:
    requires: [main]
  join_job:
    requires: [internal_fork, sd@4810:external_fork, sd@4811:external_fork]
